<a href="https://colab.research.google.com/github/sharan16/DeepLearning/blob/master/deeplearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
x1 =  tf.constant([[2],[1],[1]])
x2 = tf.constant([1,2,3,4])
result = tf.multiply(x1,x2)
print (result)
with tf.Session() as sess:
  output = sess.run(result)
  print(output)


Tensor("Mul:0", shape=(3, 4), dtype=int32)
[[2 4 6 8]
 [1 2 3 4]
 [1 2 3 4]]


In [0]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("/tmp/data/", one_hot =True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use urllib or similar directly.
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /tmp/data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from t

In [0]:
num_nodes_hl1 = 500
num_nodes_hl2 = 500
num_nodes_hl3 = 500
num_classes = 10
batch_size = 100
x = tf.placeholder('float' ,[None,784])
y = tf.placeholder('float')


In [0]:
def nn_model(data):
    print(data)
    hidden_1_layer =  {'weights': tf.Variable(tf.random_normal([784,num_nodes_hl1])),
                       'biases':tf.Variable(tf.random_normal([num_nodes_hl1]))}
    hidden_2_layer =  {'weights': tf.Variable(tf.random_normal([num_nodes_hl1,num_nodes_hl2])),
                       'biases':tf.Variable(tf.random_normal([num_nodes_hl2]))}
    hidden_3_layer =  {'weights': tf.Variable(tf.random_normal([num_nodes_hl2,num_nodes_hl3])),
                       'biases':tf.Variable(tf.random_normal([num_nodes_hl3]))}
    output_layer =  {'weights': tf.Variable(tf.random_normal([num_nodes_hl3,num_classes])),
                       'biases':tf.Variable(tf.random_normal([num_classes]))}
    l1= tf.add(tf.matmul(data,hidden_1_layer['weights']),hidden_1_layer['biases'])
    l1 = tf.nn.relu(l1)
    
    l2= tf.add(tf.matmul(l1,hidden_2_layer['weights']),hidden_2_layer['biases'])
    l2 = tf.nn.relu(l2)
    
    l3= tf.add(tf.matmul(l2,hidden_3_layer['weights']),hidden_3_layer['biases'])
    l3 = tf.nn.relu(l3)
    
    output = tf.add(tf.matmul(l3,output_layer['weights']), output_layer['biases'])
    return output
    

In [0]:
def train_nn(x):
    prediction =   nn_model(x)
    cost = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits(logits=prediction, labels=y) )
    optimizer = tf.train.AdamOptimizer().minimize(cost)
    
    num_epochs = 10
    with tf.Session() as sess:
      sess.run(tf.global_variables_initializer())
      for epoch in range(num_epochs):
        epoch_loss = 0
        for _ in range((int(mnist.train.num_examples/batch_size))):
          epoch_x, epoch_y = mnist.train.next_batch(batch_size)
          _, c = sess.run([optimizer,cost],feed_dict= {x : epoch_x,y: epoch_y})
          epoch_loss += c
        print('Epoch', epoch,'completed out of' , num_epochs,'loss:',epoch_loss)
      correct = tf.equal(tf.argmax(prediction,1), tf.argmax(y,1))
      accuracy = tf.reduce_mean(tf.cast(correct,'float'))
      print('Accuracy: ',accuracy.eval({x:mnist.test.images,y:mnist.test.labels}))

In [113]:
train_nn(x)

Tensor("Placeholder:0", shape=(?, 784), dtype=float32)


FailedPreconditionError: ignored