<a href="https://colab.research.google.com/github/sharan16/DeepLearning/blob/master/FlightDelay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import tensorflow as tf

#Importing data set
df_raw = pd.read_csv("https://raw.githubusercontent.com/junjun99/Flight-Delay/master/flight.csv")

df_raw.head()
df_raw.describe()

YEAR       QUARTER  ...  ACTUAL_ELAPSED_TIME      DISTANCE
count  11231.0  11231.000000  ...         11043.000000  11231.000000
mean    2016.0      2.544475  ...           179.661233   1161.031965
std        0.0      1.090701  ...            77.940399    643.683379
min     2016.0      1.000000  ...            75.000000    509.000000
25%     2016.0      2.000000  ...           117.000000    594.000000
50%     2016.0      3.000000  ...           149.000000    907.000000
75%     2016.0      3.000000  ...           236.000000   1927.000000
max     2016.0      4.000000  ...           428.000000   2422.000000

[8 rows x 21 columns]

In [0]:
# Dropping unwanted features/ Pre-proccessing step 1
df = df_raw.copy()
df.drop(['YEAR','QUARTER','MONTH','DAY_OF_MONTH','DEP_DELAY','CRS_DEP_TIME','TAIL_NUM','DAY_OF_WEEK','UNIQUE_CARRIER','ORIGIN','DEST','ARR_TIME', 'ARR_DELAY','CANCELLED','DIVERTED','CRS_ELAPSED_TIME','ACTUAL_ELAPSED_TIME',],axis = 1,inplace=True)

#Dropping invalid data
df.dropna(inplace = True)
df.isna().any()

FL_NUM               False
ORIGIN_AIRPORT_ID    False
DEST_AIRPORT_ID      False
DEP_TIME             False
DEP_DEL15            False
CRS_ARR_TIME         False
ARR_DEL15            False
DISTANCE             False
dtype: bool

In [0]:
df.head()

FL_NUM  ORIGIN_AIRPORT_ID  ...  ARR_DEL15  DISTANCE
0    1399              10397  ...        0.0    2182.0
1    1476              11433  ...        0.0     528.0
2    1597              10397  ...        0.0    2182.0
3    1768              14747  ...        0.0    1399.0
4    1823              14747  ...        0.0    1927.0

[5 rows x 8 columns]

In [0]:
from scipy import stats
stats.describe(df['ARR_DEL15'])

DescribeResult(nobs=11043, minmax=(0.0, 1.0), mean=0.12451326632255727, variance=0.10901958511198007, skewness=2.274531707800145, kurtosis=3.1734944897882427)

In [0]:
import numpy as np

#One hot encode output data
y = tf.keras.utils.to_categorical(df['ARR_DEL15'].values)

x_df = df.copy()
x_df.drop('ARR_DEL15', axis = 1, inplace = True)

#Input data
x = x_df.values

print(x)
print(y)
print(np.size(x,0))
print(np.size(y,0))



[[ 1399. 10397. 14747. ...     0.  2143.  2182.]
 [ 1476. 11433. 13487. ...     0.  1435.   528.]
 [ 1597. 10397. 14747. ...     0.  1215.  2182.]
 ...
 [ 1823. 11433. 14747. ...     0.  2210.  1927.]
 [ 1901. 10397. 14747. ...     0.  1806.  2182.]
 [ 2005. 10397. 11433. ...     0.   925.   594.]]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
11043
11043


In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [0]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(5,input_shape = (7,),activation=tf.nn.relu),
    tf.keras.layers.Dense(10,activation=tf.nn.relu),
    tf.keras.layers.Dense(2, activation=tf.nn.softmax)
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
print(model.summary())

model.fit(x_train,y_train,epochs = 10)


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_61 (Dense)             (None, 5)                 40        
_________________________________________________________________
dense_62 (Dense)             (None, 10)                60        
_________________________________________________________________
dense_63 (Dense)             (None, 2)                 22        
Total params: 122
Trainable params: 122
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/10
8834/8834 [==============================] - 1s 76us/sample - loss: 2.0143 - acc: 0.8750
Epoch 2/10
8834/8834 [==============================] - 0s 48us/sample - loss: 2.0143 - acc: 0.8750
Epoch 3/10
8834/8834 [==============================] - 0s 48us/sample - loss: 2.0143 - acc: 0.8750
Epoch 4/10
8834/8834 [==============================] - 0s 46us/sample - loss: 2.0143 - acc: 0.8750
Epo